version: "3"
services:
  city-groove:
    image: city-groove
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sa
      - MYSQL_DATABASE=citygroove
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=sa